cmake_minimum_required(VERSION 2.8.9)

if(BUILD_ALL_SAMPLES)
    add_subdirectory( audio )
    add_subdirectory( card_services )
    add_subdirectory( config )
    add_subdirectory( data )
    add_subdirectory( loc )
    add_subdirectory( phone )
    add_subdirectory( platform )
    add_subdirectory( power )
    add_subdirectory( sensor )
    add_subdirectory( serving_system )
    add_subdirectory( sms )
    add_subdirectory( subscription )
    add_subdirectory( tel)
    add_subdirectory( thermal )
endif(BUILD_ALL_SAMPLES)
add_subdirectory( cv2x )
