cmake_minimum_required(VERSION 2.8.9)

if(BUILD_ALL_SAMPLES)
    if((NOT BUILD_FOR_SIMULATION) AND (MACHINE_HAS_CV2X_ONLY OR MACHINE_HAS_CV2X))
        add_subdirectory( cv2x_tcp_app )
        add_subdirectory( cv2x_rx_app )
        add_subdirectory( cv2x_tx_app )
        add_subdirectory( cv2x_tx_service_status_app )
        add_subdirectory( cv2x_tx_report_sample_app )
    endif((NOT BUILD_FOR_SIMULATION) AND (MACHINE_HAS_CV2X_ONLY OR MACHINE_HAS_CV2X))
endif(BUILD_ALL_SAMPLES)

if((MACHINE_HAS_CV2X_ONLY OR MACHINE_HAS_CV2X) AND (NOT BUILD_FOR_SIMULATION))
    add_subdirectory( cv2x_get_status_app )
    add_subdirectory(cv2x_tm_app)
endif((MACHINE_HAS_CV2X_ONLY OR MACHINE_HAS_CV2X) AND (NOT BUILD_FOR_SIMULATION))
