#  Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#  SPDX-License-Identifier: BSD-3-Clause-Clear

### Logger settings ###

# CONSOLE_LOG_LEVEL, FILE_LOG_LEVEL and SYSLOG_LOG_LEVEL
# specify the threshold for log messages

# CONSOLE_LOG_LEVEL enables console logging
# FILE_LOG_LEVEL enables file based logging. Default path LOG_FILE_PATH.
# SYSLOG_LOG_LEVEL enabled syslog logging.
#
# Possible LOG_LEVEL values are NONE, PERF, ERROR, WARNING, INFO, DEBUG
# NONE - No logging.
# PERF - Prints messages with nanoseconds precision timestamp.
# ERROR - Very minimal logging.Prints perf and error messages only.
# WARNING - Prints perf, error and warning messages.
# INFO - Prints perf, errors, warning and information messages.
# DEBUG - Full logging including debug messages.It is intended for debugging purposes only.

CONSOLE_LOG_LEVEL=NONE
FILE_LOG_LEVEL=NONE
SYSLOG_LOG_LEVEL=NONE

# TELUX_LOG_COMPONENT_FILTER allows one or more whitelist which SDK technology domain should be
# logged.
# 0 - All logs are printed.
# 1 - Audio logs are printed.
# 2 - CV2X logs are printed.
# 3 - Data logs are printed.
# 4 - Location logs are printed.
# 5 - Power logs are printed.
# 6 - Telephony logs are printed.
# 7 - Thermal logs are printed.
# 8 - Sensor logs are printed.
# 9 - Platform logs are printed.
# 10 - Security logs are printed.
#
# For logging all component
# use TELUX_LOG_COMPONENT_FILTER=0
#
# For logging more than one component like cv2x and audio (comma separated)
# use TELUX_LOG_COMPONENT_FILTER=2,1

TELUX_LOG_COMPONENT_FILTER=0

# MAX_LOG_FILE_SIZE specifies the maximum allowed size(in bytes) of the log file
# When the log file reaches its maximum size, it is saved as tel.log.backup.
# If the log file again reaches the max, it will be saved again overwriting the previous
# tel.log.backup file.
# So at a given time only one tel.log and tel.backup will exist in system.
# Default MAX_LOG_FILE_SIZE is 5 Mega Bytes.

MAX_LOG_FILE_SIZE=5242880

# LOG_PREFIX_DATE_TIME used to prefix date and time on every log Message
# FALSE - logs with filename and line number, this is default option
# TRUE - logs with date, time, filename and line number

LOG_PREFIX_DATE_TIME=TRUE

# LOG_FILE_PATH specifies the path of the log file
# Specifies the log file path, by default the path is, from where the application runs.

#LOG_FILE_PATH=/data/vendor/telsdk

# LOG_FILE_NAME specifies the name of the log file to be used

LOG_FILE_NAME=tel.log

### Multi SIM settings ###
# MULTISIM_CONFIG specifies type of multi SIM configuration supported. By default multi SIM
# configuration is not enabled.
# For Dual SIM Dual Active use - dsda
# For Dual SIM Dual Standby use - dsds
#
# MULTISIM_CONFIG=dsda

###Reading Report Settings ###
#Report simulation types:0 and default : Fixed Canned values
#1 : Taken from File, File having values every 100 msecs, File Name in : REPORT_FILE_NAME
REPORT_SIMULATION_TYPE = 1

#File to be reported: Valid filename: PRE-RECORDED_LOCATION_DATA.csv,
#full path name can be provided ex: /home/user/PRE-RECORDED_LOCATION_DATA.csv
LOCATION_REPORT_FILE_NAME = PRE-RECORDED_LOCATION_DATA.csv

###Data Settings###
DATA_INTERFACE_NAME = eth0
