#  Changes from Qualcomm Innovation Center are provided under the following license:
#  Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#  SPDX-License-Identifier: BSD-3-Clause-Clear

###Logger Settings##
# LoggerLevel levels: DISABLE_ALL, ERROR, WARNING, INFO, DEBUG
LOGGER_LEVEL = DEBUG
# LoggerType types: CONSOLE_LOG, FILE_LOG, CONSOLE_FILE_LOG
LOGGER_TYPE = FILE_LOG
# To specify log file name
LOG_FILE_NAME = tel.log

### Multi SIM settings ###
# MULTISIM_CONFIG specifies type of multi SIM configuration supported. By default multi SIM
# configuration is not enabled.
# For Dual SIM Dual Active use - dsda
# For Dual SIM Dual Standby use - dsds
#
# MULTISIM_CONFIG=dsda

###Reading Report Settings ###
#Report simulation types:0 and default : Fixed Canned values
#1 : Taken from File, File having values every 100 msecs, File Name in : REPORT_FILE_NAME
REPORT_SIMULATION_TYPE = 1

#File to be reported: Valid filename: PRE-RECORDED_LOCATION_DATA.csv,
#full path name can be provided ex: /home/user/PRE-RECORDED_LOCATION_DATA.csv
LOCATION_REPORT_FILE_NAME = PRE-RECORDED_LOCATION_DATA.csv
