# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
[program:telsdk_simulation_server]
command=/usr/bin/telsdk_simulation_server
user=root
autostart=true
autorestart=true