# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

### Telux Power Reference Demon Slave Setting ###

[SOCKET_COMMUNICATION]
# INSTALL_DATA_FILTER_FOR_SOCKET: Enables or disables the installation of data filters for
#           communication sockets before suspend.
# - ENABLE:  Installs an additional filter for the configured socket connection
#            along with filters specified in NAOIP_FILTER_CONFIG_FILE.
# - DISABLE: Before device suspend, does not install any additional filter for this socket
#            communication section.
#
INSTALL_DATA_FILTER_FOR_SOCKET=DISABLE

# For Application ROLE = CLIENT:
#   - It will use the client address from the data call started on the
#     specified profile and SIM, and a randomly assigned client port.
#   - The destination server address and port are mandatory to establish communication.
#
# For Application ROLE = SERVER:
#   - The server address used for listening will be derived from the started data call.
#   - The server port is mandatory to start listening.
ROLE=CLIENT

# Provide transport protocol such as TCP or UDP
TRANSPORT_PROTOCOL=TCP

# If the transport protocol is TCP, when the device is in suspend mode, to keep the TCP session
# active for a long time, sending keep-alive messages can be offloaded to the modem
# to avoid waking the device.
TCP_KEEP_ALIVE=ENABLE

# Keep-alive packet interval is in milliseconds and is expected to be greater than or equal to
# 60000.
TCP_KEEP_ALIVE_PACKET_INTERVAL=60000

# IP_FAMILY represents whether the IP connection is IPv4 (IP_FAMILY=4) or IPv6 (IP_FAMILY=6)
IP_FAMILY=4

# Start the data call on the profile and slot specified below before establishing the IP connection.
# If not specified, the default profile will be used.
PROFILE_ID=1

# Logical slot ID
# If not specified, the default SIM will be used.
SLOT_ID=1

# Specify the data interface name that needs to be used for socket connection
# In case of external application processor or virtual machine, it's recommended to configure
# interface name; otherwise, the interface from data call will be attempted to be used.
DATA_INTERFACE_NAME=mhi_eth0

# Apps have been granted SELinux permission to use destination context `unreserved_port_t`.
# The unreserved port range is 1024–65535, but some ports within this range are assigned to other
# SELinux contexts, e.g., Hadoop DataNode port: 50010, complex main port: 5000, X server ports:
# 6000–6020, etc. Fewer or no reserved ports are found between 51500–65535.
# To avoid SELinux denial, make sure the port is unreserved or run the device in permissive mode.
#
# SERVER_ADDRESS and SERVER_PORT must be configured accordingly.
# For Application ROLE = CLIENT:
#   - The destination server address and port are mandatory to establish communication.
#
# For Application ROLE = SERVER:
#   - The server address used for listening will be derived from the started data call.
#   - The server port is mandatory to start listening.
SERVER_ADDRESS=
SERVER_PORT=

# If multiple socket communications are expected, duplicate the SOCKET_COMMUNICATION section for
# each socket connection.
#
#[SOCKET_COMMUNICATION]
#INSTALL_DATA_FILTER_FOR_SOCKET=DISABLE
#ROLE=CLIENT
#TRANSPORT_PROTOCOL=TCP
#TCP_KEEP_ALIVE=ENABLE
#TCP_KEEP_ALIVE_PACKET_INTERVAL=60000
#IP_FAMILY=4
#PROFILE_ID=1
#SLOT_ID=1
#DATA_INTERFACE_NAME=mhi_eth0
#SERVER_ADDRESS=
#SERVER_PORT=
