### make ecall settings ###

#DIAL_NUMBER specifies the phone number of the remote party
DIAL_NUMBER = +18989531755


### send sms settings ###

#RECEIVER_NUMBER specifies the phone number of the receiver
RECEIVER_NUMBER = +18989531755

#MESSAGE specifies the text message which is sent to the remote party
MESSAGE = TEST message
