#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear

### chrony-sock Setting ###

CONSOLE_LOG_LEVEL=NONE
FILE_LOG_LEVEL=NONE
DIAG_LOG_LEVEL=NONE
LOGCAT_LOG_LEVEL=NONE
SYSLOG_LOG_LEVEL=NONE

# The time difference (in milliseconds) between the update time and system time,
# beyond which the update can be applied to the system.
time.hysteresis.threshold=1000

# Enable CV2X(SLSS) time or not.
enable.cv2x.time=FALSE

# Enable cellular network time or not.
enable.network.time=FALSE

# The slot ID of the SIM card that provides cellular network time.
network.time.slot=1

# Enable updating delta time or not.
enable.delta.update=FALSE
