/*
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted (subject to the limitations in the
 * disclaimer below) provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials provided
 *       with the distribution.
 *
 *     * Neither the name of Qualcomm Innovation Center, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
 * GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
 * HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

 syntax = "proto3";

 package telStub;
 import "google/protobuf/empty.proto";
 import "common_simulation.proto";
 import "event_simulation.proto";

 /*******************************************************************
  * Services Definition                                             *
  *******************************************************************/
 service CardService {
     rpc InitService(google.protobuf.Empty) returns (commonStub.GetServiceStatusReply) {}
     rpc GetServiceStatus(google.protobuf.Empty) returns (commonStub.GetServiceStatusReply) {}
     rpc IsSubsystemReady(google.protobuf.Empty) returns (commonStub.IsSubsystemReadyReply) {}
     rpc CleanUpService(google.protobuf.Empty) returns (google.protobuf.Empty) {}
     rpc GetCardState(GetCardStateRequest) returns (GetCardStateReply) {}
     rpc GetSupportedApps(GetSupportedAppsRequest) returns (GetSupportedAppsReply) {}
     rpc ReadEFLinearFixed(ReadEFLinearFixedRequest) returns (ReadEFLinearFixedReply) {}
     rpc ReadEFLinearFixedAll(ReadEFLinearFixedAllRequest) returns (ReadEFLinearFixedAllReply) {}
     rpc ReadEFTransparent(ReadEFTransparentRequest) returns (ReadEFTransparentReply) {}
     rpc WriteEFLinearFixed(WriteEFLinearFixedRequest) returns (WriteEFLinearFixedReply) {}
     rpc WriteEFTransparent(WriteEFTransparentRequest) returns (WriteEFTransparentReply) {}
     rpc RequestEFAttributes(EFAttributesRequest) returns (RequestEFAttributesReply) {}
     rpc OpenLogicalChannel(OpenLogicalChannelRequest) returns (OpenLogicalChannelReply) {}
     rpc CloseLogicalChannel(CloseLogicalChannelRequest) returns (CloseLogicalChannelReply) {}
     rpc TransmitAPDU(TransmitAPDURequest) returns (TransmitAPDUReply) {}
     rpc TransmitBasicAPDU(TransmitBasicAPDURequest) returns (TransmitBasicAPDUReply) {}
     rpc SetCardLock(SetCardLockRequest) returns (SetCardLockReply) {}
     rpc QueryPin1Lock(QueryPin1LockRequest) returns (QueryPin1LockReply) {}
     rpc ChangePinLock(ChangePinLockRequest) returns (ChangePinLockReply) {}
     rpc UnlockByPin(UnlockByPinRequest) returns (UnlockByPinReply) {}
     rpc UnlockByPuk(UnlockByPukRequest) returns (UnlockByPukReply) {}
     rpc QueryFdnLock(QueryFdnLockRequest) returns (QueryFdnLockReply) {}
     rpc updateSimStatus(updateSimStatusRequest) returns (updateSimStatusReply){}
     rpc CardPower(CardPowerRequest) returns (CardPowerResponse) {}
     rpc exchangeSimIO(exchangeSimIORequest) returns (exchangeSimIOReply) {}
     rpc requestEid(requestEidRequest) returns (requestEidReply) {}
 }
 service PhoneService {
     rpc InitService(google.protobuf.Empty) returns (commonStub.GetServiceStatusReply) {}
     rpc GetServiceStatus(google.protobuf.Empty) returns (commonStub.GetServiceStatusReply) {}
     rpc IsSubsystemReady(google.protobuf.Empty) returns (commonStub.IsSubsystemReadyReply) {}
     rpc GetSubscription(GetSubscriptionRequest) returns (Subscription) {}
     rpc GetAllSubscription(google.protobuf.Empty) returns (GetAllSubscriptionsReply) {}
 }
 service SmsService {
     rpc InitService (commonStub.GetServiceStatusRequest) returns (commonStub.GetServiceStatusReply) {}
     rpc GetServiceStatus(commonStub.GetServiceStatusRequest) returns (commonStub.GetServiceStatusReply) {}
     rpc SendSmsWithoutSmsc (SendSmsWithoutSmscRequest) returns (SendSmsWithoutSmscReply) {}
     rpc GetSmscAddress (GetSmscAddressRequest) returns (GetSmscAddressReply) {}
     rpc SetSmscAddress (SetSmscAddressRequest) returns (SetSmscAddressReply) {}
     rpc GetMessageAttributes (GetMessageAttributesRequest) returns (GetMessageAttributesReply) {}
     rpc SendSms (SendSmsRequest) returns (SendSmsReply) {}
     rpc SendRawSms (SendRawSmsRequest) returns (SendRawSmsReply) {}
     rpc RequestSmsMessageList (RequestSmsMessageListRequest) returns (RequestSmsMessageListReply){}
     rpc ReadMessage (ReadMessageRequest) returns (ReadMessageReply) {}
     rpc DeleteMessage (DeleteMessageRequest) returns (DeleteMessageRequestReply) {}
     rpc RequestPreferredStorage (RequestPreferredStorageRequest)
        returns (RequestPreferredStorageReply) {}
     rpc SetPreferredStorage (SetPreferredStorageRequest) returns (SetPreferredStorageReply) {}
     rpc SetTag (SetTagRequest) returns (SetTagReply) {}
     rpc RequestStorageDetails (RequestStorageDetailsRequest)
        returns (RequestStorageDetailsReply) {}
     rpc IsMemoryFull (IsMemoryFullRequest) returns (IsMemoryFullReply) {}
 }


 /*******************************************************************
  * Messages Definition                                             *
  *******************************************************************/

message GetCardStateRequest {
     int32 phone_id = 1;
}

 message GetCardStateReply{
     CardState card_state = 1;
 }

 message CardPowerRequest{
    int32 phone_id = 1;
    bool powerup = 2;
 }
 message CardPowerResponse{
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }
 message Subscription {
     string carrier_name = 1;
     string icc_id = 2;
     int32 mcc = 3;
     int32 mnc = 4;
     string mobile_country_code = 5;
     string mobile_network_code = 6;
     string phone_number = 7;
     int32 slot_id = 8;
     string imsi = 9;
     string gid_1 = 10;
     string gid_2 = 11;
 }

 message GetAllSubscriptionsReply {
    repeated Subscription subscriptions = 1;
 }

 message GetSubscriptionRequest{
     int32 phone_id = 1;
 }

 message SubscriptionEvent {
     int32 phone_id = 1;
 }

 enum AppType {
     APPTYPE_UNKNOWN = 0;
     APPTYPE_SIM = 1;
     APPTYPE_USIM = 2;
     APPTYPE_RUIM = 3;
     APPTYPE_CSIM = 4;
     APPTYPE_ISIM = 5;
 }

 enum AppState {
    PPSTATE_UNKNOWN = 0;
    APPSTATE_DETECTED = 1;
    APPSTATE_PIN = 2;
    APPSTATE_PUK = 3;
    APPSTATE_SUBSCRIPTION_PERSO = 4;
    APPSTATE_READY = 5;
 }

 message CardApp {
     AppType app_type = 1;
     AppState app_state = 2;
     string app_id = 3;
 }

 message GetSupportedAppsRequest {
     int32 slot_id = 1;
 }

 message GetSupportedAppsReply {
     repeated CardApp card_apps = 1;
 }

 // --- CardService ---

 enum CardState {
     CARDSTATE_ABSENT = 0;
     CARDSTATE_PRESENT = 1;
     CARDSTATE_ERROR = 2;
     CARDSTATE_RESTRICTED = 3;
     CARDSTATE_UNKNOWN = -1;
 }

 message IccResult {
     int32 sw1 = 1;
     int32 sw2 = 2;
     string pay_load = 3;
     repeated int32 data = 4;
 }

 message ReadEFLinearFixedRequest {
     int32 slot_id = 1;
     string file_path = 2;
     int32 file_id = 3;
     int32 record_number = 4;
     string aid = 5;
 }

 message ReadEFLinearFixedReply {
     IccResult result = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }

 message ReadEFLinearFixedAllRequest {
     int32 slot_id = 1;
     string file_path = 2;
     int32 file_id = 3;
     string aid = 4;
 }

 message ReadEFLinearFixedAllReply {
     repeated IccResult records = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }

 message ReadEFTransparentRequest {
     int32 slot_id = 1;
     string file_path = 2;
     int32 file_id = 3;
     int32 size = 4;
     string aid = 5;
 }

 message ReadEFTransparentReply {
     IccResult result = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }
 message WriteEFLinearFixedRequest {
     int32 slot_id = 1;
     string file_path = 2;
     int32 file_id = 3;
     int32 record_number = 4;
     repeated int32 data = 5;
     string pin2 = 6;
     string aid = 7;
 }

 message WriteEFLinearFixedReply {
     IccResult result = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     repeated int32 data = 5;
     bool isCallback = 6;
 }

 message WriteEFTransparentRequest {
     int32 slot_id = 1;
     string file_path = 2;
     int32 file_id = 3;
     repeated int32 data = 4;
     string aid = 5;
 }

 message WriteEFTransparentReply {
     IccResult result = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }
 enum EfType {
     UNKNOWN = 0;
     TRANSPARENT = 1;
     LINEAR_FIXED = 2;
 }
 enum CardLockType {
   PIN1 = 0;
   PIN2 = 1;
   PUK1 = 2;
   PUK2 = 3;
   FDN  = 4;
};

 message EFAttributesRequest {
     int32 slot_id = 1;
     EfType ef_type = 2;
     string file_path = 3;
     int32 file_id = 4;
     string aid = 5;
 }

 message FileAttributes {
     int32 file_size = 1;
     int32 record_size = 2;
     int32 record_count = 3;
 }

 message RequestEFAttributesReply {
     IccResult result = 1;
     FileAttributes file_attributes = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
     bool isCallback = 6;
 }

 message OpenLogicalChannelRequest {
     int32 phone_id = 1;
     string app_id = 2;
 }

 message OpenLogicalChannelReply {
     int32 channel_id = 1;
     IccResult result = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
     bool isCallback = 6;
 }

 message CloseLogicalChannelRequest {
     int32 phone_id = 1;
     int32 channel_id = 2;
 }
 message CloseLogicalChannelReply {
     commonStub.ErrorCode error = 1;
     commonStub.Status status = 2;
     int32 delay = 3;
     bool isCallback = 4;
 }

 message TransmitAPDURequest {
     int32 phone_id = 1;
     int32 cla = 2;
     int32 instruction = 3;
     int32 p1 = 4;
     int32 p2 = 5;
     int32 p3 = 6;
     repeated int32 data = 7;
 }

 message TransmitAPDUReply {
     IccResult result = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }

 message exchangeSimIORequest {
     int32 phone_id = 1;
     int32 fileId = 2;
     int32 command = 3;
     int32 p1 = 4;
     int32 p2 = 5;
     int32 p3 = 6;
     repeated int32 data = 7;
 }

 message exchangeSimIOReply {
     IccResult result = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }

 message requestEidRequest {
    int32 phone_id = 1;
 }

 message requestEidReply {
    string eid = 1;
    commonStub.Status status = 2;
    commonStub.ErrorCode error = 3;
    int32 delay = 4;
    bool isCallback = 5;
 }

 message TransmitBasicAPDURequest {
     int32 phone_id = 1;
     int32 cla = 2;
     int32 instruction = 3;
     int32 p1 = 4;
     int32 p2 = 5;
     int32 p3 = 6;
     repeated int32 data = 7;
 }

 message TransmitBasicAPDUReply {
     IccResult result = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }
 message SetCardLockRequest {
     int32 phone_id = 1;
     CardLockType lock_type = 2;
     string pwd = 3;
     bool enable = 4;
     string aid = 5;
 }

 message SetCardLockReply {
     int32 retry_count = 1;
     bool iscardinfochanged = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
     bool isCallback = 6;
 }

 message QueryPin1LockRequest {
     int32 phone_id = 1;
 }

 message QueryPin1LockReply {
     bool state = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool isCallback = 5;
 }

 message ChangePinLockRequest {
     int32 phone_id = 1;
     CardLockType lock_type = 2;
     string old_pin = 3;
     string new_pin = 4;
     string aid = 5;
 }

 message ChangePinLockReply {
     int32 retry_count = 1;
     bool isCardInfoChanged = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
     bool isCallback = 6;
 }

 message UnlockByPinRequest {
     int32 phone_id = 1;
     CardLockType lock_type = 2;
     string pin = 3;
     string aid = 4;
 }

 message UnlockByPinReply {
     int32 retry_count = 1;
     bool isCardInfoChanged = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
     bool isCallback = 6;
 }

 message UnlockByPukRequest {
     int32 phone_id = 1;
     CardLockType lock_type = 2;
     string puk = 3;
     string new_pin = 4;
     string aid = 5;
 }

 message UnlockByPukReply {
     int32 retry_count = 1;
     bool isCardInfoChanged = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
     bool isCallback = 6;
 }

 message QueryFdnLockRequest {
     int32 phone_id = 1;
 }

 message QueryFdnLockReply {
     bool is_available = 1;
     bool state = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
     bool isCallback = 6;
 }
 message updateSimStatusRequest {
     int32 phone_id = 1;
 }

 message updateSimStatusReply{
     CardState card_state = 1;
     repeated CardApp card_apps = 2;
     commonStub.ErrorCode error = 3;
     commonStub.Status status = 4;
     int32 delay = 5;
 }

// --- SmsService ---

 message SendSmsWithoutSmscRequest {
     int32 phone_id = 1;
     string number = 2;
     string message = 3;
     bool delivery_status = 4;
 }
 message SendSmsWithoutSmscReply {
    int32 noofsegments = 1;
    commonStub.Status status = 2;
    commonStub.ErrorCode sentCallback_errorcode = 3;
    int32 sentcallback_callbackdelay = 4;
    string sentcallback_msgrefs = 5;
    commonStub.ErrorCode deliverycallback_errorCode = 6;
    int32 deliveryCallback_callbackDelay = 7;
 }

 message GetSmscAddressRequest {
     int32 phone_id = 1;
 }

 message GetSmscAddressReply {
     string smsc_address = 1;
     commonStub.ErrorCode error = 2;
     commonStub.Status status = 3;
     int32 delay = 4;
     bool iscallback = 5;
 }

 message SetSmscAddressRequest {
     int32 phone_id = 1;
     string number = 2;
 }

 message SetSmscAddressReply {
     commonStub.ErrorCode error = 1;
     commonStub.Status status = 2;
     int32 delay = 3;
     bool iscallback = 4;
 }

 message GetMessageAttributesRequest {
     string message = 1;
     int32 phone_id = 2;
 }

 message MessageAttributes {
     enum SmsEncoding {
         GSM7 = 0;
         GSM8 = 1;
         UCS2 = 2;
         UNKNOWN = 3;
     }
     SmsEncoding encoding = 1;
     int32 number_of_segments = 2;
     int32 segment_size = 3;
     int32 number_of_chars_left_in_last_segment = 4;
 }

 message GetMessageAttributesReply {
     MessageAttributes message_attribute = 1;
 }

 message SendSmsRequest {
     int32 phone_id = 1;
 }
 message Deliverycallback {
    commonStub.ErrorCode ondeliveryreport_errorCode = 1;
    int32 ondeliveryreportmsgRef = 2;
    int32 deliverycallbackdelay = 3;
 }

 message SendSmsReply {
     int32 noofsegments = 1;
     commonStub.Status status = 2;
     commonStub.ErrorCode smsresponsecb_errorCode = 3;
     int32 smsresponsecb_callbackDelay = 4;
     string sentcallback_msgrefs = 5;
     repeated Deliverycallback records = 6;
 }

 message PduBuffer {
     repeated string pdu_buffer = 1;
 }

 message SendRawSmsRequest {
     int32 phone_id = 1;
     int32 size = 2;
 }

 message SendRawSmsReply {
     string reciever_address = 1;
     commonStub.Status status = 2;
     commonStub.ErrorCode smsresponsecb_errorCode = 3;
     int32 smsresponsecb_callbackDelay = 4;
     string sentcallback_msgrefs = 5;
     repeated Deliverycallback records = 6;
 }

 message SmsTagType {
    enum TagType {
        MT_READ = 0;
        UNKNOWN = -1;
        MT_NOT_READ = 1;
    }
 }

 message RequestSmsMessageListRequest {
    int32 phone_id = 1;
    SmsTagType.TagType tag_type = 2;
 }

 message SmsMetaInfo {
    bool isMetaInfoValid = 1;
    uint32 msg_index = 2;
    SmsTagType.TagType tag_type = 3;
 }

 message RequestSmsMessageListReply {
    repeated SmsMetaInfo meta_info = 1;
    commonStub.ErrorCode error = 2;
    commonStub.Status status = 3;
    int32 delay = 4;
    bool iscallback = 5;
 }

 message ReadMessageRequest {
    int32 phone_id = 1;
    uint32 msg_index = 2;
 }

 message ReadMessageReply {
    SmsMessage sms_message = 1;
    commonStub.ErrorCode error = 2;
    commonStub.Status status = 3;
    int32 delay = 4;
    bool iscallback = 5;
 }

 message IsMemoryFullRequest {
    int32 phone_id = 1;
 }

 message IsMemoryFullReply {
    bool ismemoryfull = 1;
 }

 message DelType {
    enum DeleteType {
        DELETE_ALL = 0;
        UNKNOWN = -1;
        DELETE_MESSAGES_BY_TAG = 1;
        DELETE_MSG_AT_INDEX = 2;
    }
 }

 message DeleteMessageRequest {
    int32 phone_id = 1;
    DelType.DeleteType del_type = 2;
    SmsTagType.TagType tag_type = 3;
    uint32 msg_index = 4;
 }
 message DeleteMessageRequestReply {
    commonStub.ErrorCode error = 1;
    commonStub.Status status = 2;
    int32 delay = 3;
    bool iscallback = 4;
 }

 message StorageType {
    enum Type {
       NONE = 0;
       UNKNOWN = -1;
       SIM = 1;
    }
 }

 message RequestPreferredStorageRequest {
    int32 phone_id = 1;
 }

 message RequestPreferredStorageReply {
    StorageType.Type storage_type = 1;
    commonStub.ErrorCode error = 2;
    commonStub.Status status = 3;
    int32 delay = 4;
    bool iscallback = 5;
 }

 message SetPreferredStorageRequest {
    int32 phone_id = 1;
    StorageType.Type storage_type = 2;
 }
 message SetPreferredStorageReply {
    commonStub.ErrorCode error = 1;
    commonStub.Status status = 2;
    int32 delay = 3;
    bool iscallback = 4;
 }

 message SetTagRequest {
    int32 phone_id = 1;
    uint32 msg_index = 2;
    SmsTagType.TagType tag_type = 3;
 }
 message SetTagReply {
    commonStub.ErrorCode error = 1;
    commonStub.Status status = 2;
    int32 delay = 3;
    bool iscallback = 4;
 }

 message RequestStorageDetailsRequest {
    int32 phone_id = 1;
 }

 message RequestStorageDetailsReply {
    uint32 max_count = 1;
    uint32 available_count = 2;
    commonStub.ErrorCode error = 3;
    commonStub.Status status = 4;
    int32 delay = 5;
    bool iscallback = 6;
 }

 message SmsMessage {
    string text = 1;
    string sender = 2;
    string receiver = 3;
    MessageAttributes.SmsEncoding encoding = 4;
    string pdu = 5;
    string pdu_buff = 6;
    uint32 messageinforef_no = 7;
    uint32 messageinfono_of_segments = 8;
    uint32 messageinfosegment_no = 9;
    bool ismetainfo_valid = 10;
    uint32 msg_index = 11;
    SmsTagType.TagType tag_type = 12;
    int32 phone_id = 13;
 }

 message cardInfoChange {
    int32 phone_id = 1;
    bool card_power = 2;
 }

 message memoryFullEvent {
    int32 phone_id = 1;
    StorageType.Type storage_type = 2;
 }