# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

### Telux Data Filter Setting ###
# This setting is used by the telux_power_refd service and can also be used in the
# telsdk_console_app to add data restrict filter.

[filter]
SOURCE_IPV4_ADDRESS =
DESTINATION_IPV4_ADDRESS =
SOURCE_IPV6_ADDRESS =
DESTINATION_IPV6_ADDRESS =
FILTER_PROTOCOL_TYPE =

TCP_SOURCE_PORT=
TCP_SOURCE_PORT_RANGE=
TCP_DESTINATION_PORT=
TCP_DESTINATION_PORT_RANGE=

UDP_SOURCE_PORT=
UDP_SOURCE_PORT_RANGE=
UDP_DESTINATION_PORT=
UDP_DESTINATION_PORT_RANGE=
SLOT_ID=