cmake_minimum_required(VERSION 2.8.9)

if(NOT BUILD_FOR_SIMULATION)
    add_subdirectory( telsdk_console_app )
    add_subdirectory( sensor_test_app )
    add_subdirectory( thermal_test_app )
    add_subdirectory( location_test_app )
    add_subdirectory( thermal_shutdown_test_app )
    add_subdirectory( modem_configurator )
    add_subdirectory( data_qos_test_app )
    add_subdirectory( filesystem_test_app )
    add_subdirectory( telux_version_app )
    add_subdirectory( wlan_test_app )

    pkg_check_modules(PWR_MGR_QMI_LIB powermanagerqmi)
    if (PWR_MGR_QMI_LIB_FOUND)
        add_subdirectory( power_test_app )
    endif (PWR_MGR_QMI_LIB_FOUND)

    if(MACHINE_HAS_CV2X_ONLY OR MACHINE_HAS_CV2X)
        add_subdirectory( cv2x_slss_rx_app)
        add_subdirectory( cv2x_tcp_test )
        add_subdirectory( cv2x_unicast_app)
        add_subdirectory( cv2x_config_app )
        add_subdirectory( cv2x_get_capabilities_app )
        add_subdirectory( cv2x_set_tx_power_app)
        add_subdirectory( cv2x_l2_id_filter_app)
        add_subdirectory( cv2x_tx_report_test_app)
    endif(MACHINE_HAS_CV2X_ONLY OR MACHINE_HAS_CV2X)

    if(NOT MACHINE_HAS_CV2X_ONLY)
        add_subdirectory( audio_console_app )
        add_subdirectory( audio_loopback_app )
    endif(NOT MACHINE_HAS_CV2X_ONLY)
endif(NOT BUILD_FOR_SIMULATION)
